#-------
#Imports
#-------
import sys
import tkinter as tk
from tkinter import ttk
import random as rand

#---------
#Variables
#---------

class TextColors:
    RESET = '\033[0m'  # Reset to default color
    BLACK = '\033[30m'
    RED = '\033[31m'
    GREEN = '\033[32m'
    YELLOW = '\033[33m'
    BLUE = '\033[34m'
    MAGENTA = '\033[35m'
    CYAN = '\033[36m'
    WHITE = '\033[37m'

background_color = '#d9cfe8'

#List of 100 random fortune cookie statements generated by Chat-GPT
fortune_cookies = (
    "A wise person is one who learns from another's mistakes.",
    "A good way to keep healthy is to eat more Chinese food.",
    "A friend is a present you give yourself.",
    "A journey of a thousand miles begins with a single step.",
    "A smile is your passport into the hearts of others.",
    "A smooth long journey! Great expectation.",
    "A surprise from the universe is about to arrive.",
    "Adventure can be real happiness.",
    "All your hard work will soon pay off.",
    "An enjoyable vacation is awaiting you.",
    "Any decision you have to make tomorrow is a good decision.",
    "As the purse is emptied the heart is filled.",
    "Be careful or you could fall for some tricks today.",
    "Bide your time, for success is near.",
    "Compliment your friends often.",
    "Don’t just spend time. Invest it.",
    "Do you believe? Endurance and persistence will be rewarded.",
    "Don’t just think, act!",
    "Do you have a quiet friend? Be nice to him.",
    "Excellence is the difference between what I do and what I am capable of.",
    "For hate is never conquered by hate. Hate is conquered by love.",
    "For the things we have to learn before we can do them, we learn by doing them.",
    "From listening comes wisdom and from speaking repentance.",
    "Get your mind set…confidence will lead you on.",
    "Good news will be brought to you by mail.",
    "Happiness begins with facing life with a smile and a wink.",
    "Happiness will bring you good luck.",
    "Happy life is just in front of you.",
    "Hard words break no bones, fine words butter no parsnips.",
    "Honesty is the best policy.",
    "If a true sense of value is to be yours it must come through service.",
    "If you have something good in your life, don’t let it go!",
    "If you’re feeling down, try throwing yourself into your work.",
    "Impending disaster is often the best way to bring peace.",
    "In the eyes of lovers, everything is beautiful.",
    "It is better to be an optimist and proven a fool than to be a pessimist and be proven right.",
    "It is better to deal with problems before they arise.",
    "It is honorable to stand up for what is right, however unpopular it seems.",
    "It is worth reviewing some old lessons.",
    "It’s not the amount of time you devote, but what you devote to the time that counts.",
    "Let the world be filled with tranquility and goodwill.",
    "Like the river flow into the sea. Something are just meant to be.",
    "Listen not to vain words of empty tongue.",
    "Love is as necessary to human beings as food and shelter.",
    "Love is on its way.",
    "Love isn’t a decision. It’s a feeling. If we could decide who to love, then, life would be much simpler, but then less magical.",
    "Love is the only medicine for a broken heart.",
    "Love will lead the way.",
    "Many will travel to hear you speak.",
    "Meditation with an old enemy is advised.",
    "Miles are covered one step at a time.",
    "New people will bring you good luck.",
    "Next time you have the opportunity, go on a rollercoaster.",
    "Now is a good time to buy stock.",
    "Now is the time to go ahead and pursue that love interest!",
    "Now is the time to try something new.",
    "Now, go take a shower.",
    "Our first and last love…is self-love.",
    "Patience is a virtue, unless its against a brick wall.",
    "Please visit us at www.wontonfood.com",
    "Put all your unhappiness aside…there is a bright future ahead.",
    "Savor your freedom – it is precious.",
    "Say hello to others. You will have a happier day.",
    "Sift through your past to get a better idea of the present.",
    "Someone you care about seeks reconciliation.",
    "Someone you care about seeks your attention.",
    "Soon life will become more interesting.",
    "Stand tall. Don’t look down upon yourself.",
    "The caterpillar does all the work but the butterfly gets all the publicity.",
    "The greatest risk is not taking one.",
    "The greatest wealth is to live content with little.",
    "The love of your life is stepping into your planet this summer.",
    "The man or woman you desire feels the same about you.",
    "The strong person understands how to withstand substantial loss.",
    "The sure way to predict the future is to invent it.",
    "The weather is wonderful.",
    "There is no mistake so great as that of being always right.",
    "There is no wisdom greater than kindness.",
    "There is no wisdom greater than kindness.",
    "To a very special person.",
    "To courage and to a very special person.",
    "Today is the conserve yourself, as things just won’t budge.",
    "Today, your mouth will be one of your outstanding features.",
    "Use your eloquence where it will do the most good.",
    "We first make our habits, and then our habits make us.",
    "Welcome change.",
    "Well-earned accomplishments are on their way, and happiness is at your door.",
    "What’s hidden in an empty box?",
    "When more become too much. It’s same as being not enough.",
    "When your heart is pure, your mind is clear.",
    "With age comes wisdom.",
    "You always bring others happiness.",
    "You are a person of culture.",
    "You are a talented storyteller.",
    "You are admired by everyone for your talent and ability.",
    "You are almost there.",
    "You are busy, but you are happy.",
    "You are generous to an extreme and always think of the other fellow.",
    "You are going on an important business trip.",
    "You are inclined to be selfish.",
    "You are interested in higher education, whether material or spiritual.",
    "You are modest and courteous.",
    "You are never selfish with your advice or your help.",
    "You are only as old as you feel.",
    "You are open-minded and quick to make new friends.",
    "You are solid and dependable.",
    "You are soon going to change your present line of work.",
    "You are talented in many ways.",
    "You are the master of every situation.",
    "You are very expressive and positive in words, act and feeling.",
    "You are working hard, or hardly working?",
    "You can be trusted with any secret.",
    "You can go far with a smile.",
    "You can see a lot just by looking.",
    "You can’t steal second base and keep your foot on first.",
    "You desire recognition and you will find it.",
    "You have a deep appreciation of the arts and music.",
    "You have a deep interest in all that is artistic.",
    "You have a friendly heart and are well admired.",
    "You have a shrewd knack for spotting insincerity.",
    "You have a yearning for perfection.",
    "You have an active mind and a keen imagination.",
    "You have an ambitious nature and may make a name for yourself.",
    "You have an unusual equipment for success. Be sure to use it properly.",
    "You have exceeded what was expected.",
    "You have had a good start. Work harder!",
    "You have the power to write your own fortune.",
    "You have yearning for perfection.",
    "You know where you are going and how to get there.",
    "You look pretty.",
    "You love challenge.",
    "You love your home and want it to be beautiful.",
    "You make people realize that there exist other beauties in the world.",
    "You never hesitate to tackle the most difficult problems.",
    "You only treasure what you lost.",
    "You seek to shield those you love and like the role of provider.",
    "You should be able to make money and hold on to it.",
    "You should be able to undertake and complete anything.",
    "You understand how to have fun with others and to enjoy your solitude.",
    "You will always be surrounded by true friends.",
    "You will always get what you want through your charm and personality.",
    "You will always have good luck in your personal affairs.",
    "You will be a great success both in the business world and society.",
    "You will be blessed with longevity.",
    "You will be pleasantly surprised tonight.",
    "You will be sharing great news with all the people you love.",
    "You will be successful in love.",
    "You will be traveling and coming into a fortune.",
    "You will be traveling in the near future, and there may be some new opportunities for you.",
    "You will be unusually successful in business.",
    "You will become a great philanthropist in your later years.",
    "You will become more and more wealthy.",
    "You will enjoy good health.",
    "You will enjoy good health; you will be surrounded by luxury.",
    "You will enjoy true happiness in your life.",
    "You will find great contentment in the daily, routine activities.",
    "You will have a fine capacity for the enjoyment of life.",
    "You will have gold pieces by the bushel.",
    "You will inherit a large sum of money.",
    "You will make change for the better.",
    "You will soon be surrounded by good friends and laughter.",
    "You will step on the soil of many countries.",
    "You will take a chance in the near future, and win.",
    "You will travel far and wide, both pleasure and business.",
    "You will travel far and wide, both for pleasure and business.",
    "You will travel to many places.",
    "You will travel to many places.",
    "You will visit the great pyramids of Egypt.",
    "Your abilities are unparalleled.",
    "Your ability is appreciated.",
    "Your ability to juggle many tasks will take you far.",
    "Your biggest virtue is your modesty.",
    "Your character can be described as natural and unrestrained.",
    "Your difficulties will strengthen you.",
    "Your dreams are never silly; depend on them to guide you.",
    "Your dreams are worth your best efforts to achieve them.",
    "Your energy returns and you get things done.",
    "Your family is young, gifted and attractive.",
    "Your first love has never forgotten you.",
    "Your happiness is before you, not behind you! Cherish it.",
    "Your hard work will payoff today.",
    "Your heart will always make itself known through your words.",
    "Your home is the center of great love.",
    "Your ideals are well within your reach.",
    "Your infinite capacity for patience will be rewarded sooner or later.",
    "Your leadership qualities will be tested and proven.",
    "Your life will be happy and peaceful.",
    "Your love life will be happy and harmonious.",
    "Your love of music will be an important part of your life.",
    "Your loyalty is a virtue, but not when it’s wedded with blind stubbornness.",
    "Your mind is creative, original and alert.",
    "Your mind is your greatest asset.",
    "Your quick wits will get you out of a tough situation.",
    "Your reputation is your wealth.",
    "Your talents will be recognized and suitably rewarded."
)



#---------
#Functions
#---------
def program_select():
    running = False
    while not running:
        action = input(TextColors.BLUE + 'Would you like the (T)erminal program or the (W)indow program?: ' + TextColors.RESET)
        if action.lower() == 't' or action.lower() == 'terminal':
            terminal_based_program()
            running = True
        elif action.lower() == 'w' or action.lower() == 'window':
            tkinter_program()
            running = True
        else:
            print(TextColors.RED + 'Input a valid command\n' + TextColors.RED)

def tkinter_program():
    root = tk.Tk()
    style = ttk.Style() 

    root.attributes('-topmost', True)

    root.title('Fortune Cookie App')
    root.geometry('450x150')
    root.minsize(width='400', height='150')

    style.configure('.', background=background_color)

    root.attributes('-topmost', True)
    container = ttk.Frame(root)
    container.pack(expand=True, fill='both')

    container_button = ttk.Frame(container)
    container_button.pack(side='bottom', pady=10)

    label_question = ttk.Label(container, text='Would you like to read a fortune?')
    label_question.pack(side='top', pady=10)

    label_fortune = ttk.Label(container, text='')
    label_fortune.pack(side='top')

    button_no = ttk.Button(container_button, text='No thanks', width=15, command=lambda: button_no_on_click())
    button_no.pack(side='right', fill='x', padx=10)
    button_yes = ttk.Button(container_button, text='Yes', width=15, command=lambda: button_yes_on_click())
    button_yes.pack(side='left', fill='x')

    def button_yes_on_click():
        text=get_fortune()
        label_fortune.config(text=text)

    def button_no_on_click():
        root.destroy()

    root.mainloop()

def terminal_based_program():
    exit = False
    while not exit:
        choice = input(TextColors.CYAN + '\nWould you like to read a fortune?(Y/N): ' + TextColors.RESET)

        if choice.lower() == 'y' or choice.lower() ==  'yes' or choice.lower() ==  'ya' or choice.lower() ==  'yah' or choice.lower() ==  'yep' or choice.lower() ==  '':
            print(TextColors.MAGENTA + get_fortune() + TextColors.RESET)      
        elif choice.lower() == 'n' or choice.lower() ==  'no' or choice.lower() ==  'na' or choice.lower() ==  'nah' or choice.lower() ==  'nope' or choice.lower() ==  'exit':
            exit = True
        else:
            print(TextColors.RED + 'Input a valid command\n' + TextColors.RED)

def get_fortune():
    random_numer = rand.randint(0,100)
    fortune = fortune_cookies[random_numer]

    return fortune


